#!/bin/bash

xgettext --language=Python --keyword=_ --output=snowmenu.pot usr/lib/snowlinux/snowMenu/snowMenu.py usr/lib/snowlinux/snowMenu/snowMenuConfig.py usr/lib/snowlinux/snowMenu/plugins/applications.py
